# Site settings
title: Doug Harper
description: "Learning Swift & iOS - Companion blog for my Swift education."
baseurl: "" 
url: "http://endodoug.github.io" 
tagline: Learning Swift & iOS 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
